# Read the Docs configuration file.
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details.

build:
  # https://docs.readthedocs.com/platform/stable/config-file/v2.html#build-os
  os: ubuntu-24.04
  tools:
    # https://docs.readthedocs.com/platform/stable/config-file/v2.html#build-tools-python
    python: '3.14'

python:
   install:
      # https://docs.readthedocs.com/platform/stable/config-file/v2.html#uv
      - method: uv
        command: sync
        groups:
           - docs

mkdocs:
  configuration: .properdocs.yml

version: 2
