# Read the Docs configuration file.
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details.

build:
  # https://docs.readthedocs.com/platform/stable/config-file/v2.html#build-os
  os: ubuntu-24.04
  tools:
    # https://docs.readthedocs.com/platform/stable/config-file/v2.html#build-tools-python
    python: '3.14'
  jobs:
    pre_create_environment:
       - asdf plugin add uv
       - asdf install uv latest
       - asdf global uv latest
    create_environment:
       - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
       - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --extra docs

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements/docs.txt

version: 2
