name: Deploy GitHub Page

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_COLOR: 1
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

concurrency:
  group: github-pages
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    if: github.repository == 'vacanza/holidays'
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78
        with:
          python-version: '3.14'
          version: '0.9.16'

      - name: Install Python
        run: uv python install "$UV_PYTHON"

      - name: Install dependencies
        run: uv sync --frozen --no-default-groups --group build --link-mode=copy

      - name: Generate ICalendar data
        run: make icalendar

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
