name: Code checks

on:
  workflow_call:

env:
  DEFAULT_PYTHON_VERSION: '3.14'
  FORCE_COLOR: 1

permissions: {}

jobs:
  pre-commit:
    name: Run pre-commit
    permissions:
      contents: read
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990  # v8.3.2
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          version-file: uv.lock

      - name: Install Python
        run: uv python install "$UV_PYTHON"

      - name: Install CI tools
        run: uv sync --frozen --no-default-groups --only-group ci --no-install-project --no-build

      - name: Cache pre-commit environments
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          key: pre-commit-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.pre-commit-config.yaml') }}
          path: ~/.cache/pre-commit

      - name: Run pre-commit
        run: uv run --frozen --no-sync pre-commit run --show-diff-on-failure --color=always --all-files
