name: Update snapshots

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  DEFAULT_PYTHON_VERSION: '3.14'
  DEFAULT_UV_VERSION: '0.11.24'

jobs:
  update-snapshots:
    name: Update snapshots
    if: github.repository == 'vacanza/holidays'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          version: ${{ env.DEFAULT_UV_VERSION }}

      - name: Install Python
        run: uv python install "$UV_PYTHON"

      - name: Install dependencies
        run: uv sync --frozen --no-dev --group build

      - name: Generate snapshots
        run: make snapshot

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1  # v8.1.1
        with:
          base: dev
          body: Automatically generated snapshots update.
          branch: update-snapshots
          commit-message: 'Update snapshots [skip ci]'
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          delete-branch: true
          title: 'chore: Update snapshots'
          token: ${{ github.token }}
