name: Update snapshots

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  DEFAULT_PYTHON_VERSION: '3.14'
  DEFAULT_UV_VERSION: '0.11.8'

jobs:
  update-snapshots:
    name: Update snapshots
    if: github.repository == 'vacanza/holidays'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          version: ${{ env.DEFAULT_UV_VERSION }}

      - name: Install Python
        run: uv python install "$UV_PYTHON"

      - name: Install dependencies
        run: uv sync --frozen --no-dev --group build

      - name: Generate snapshots
        run: make snapshot

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1  # v8.1.1
        with:
          base: dev
          body: Automatically generated snapshots update.
          branch: update-snapshots
          commit-message: 'Update snapshots [skip ci]'
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          delete-branch: true
          title: 'chore: Update snapshots'
          token: ${{ github.token }}
